### ISSUE TITLE
Error: db plugin not installed

### ISSUE THREAD

**Issue by lylax47** [czcorpus/kontext#1072]
Is there still something I am missing or have not correctly indicated in the config?
-------------

    <plugins>
        <db>
            <module>redis_db</module>
            <db_path extension-by="default"> var/lib/redis/6379</db_path>
            <host extension-by="default">127.0.0.1</host>
            <port extension-by="default">6379</port>
            <id extension-by="default">0</id>
        </db>
    ...
    </plugins>

 I am now getting the following error:
-----------

[Wed Apr 20 15:41:52 2016] [error] [client 127.0.0.1] mod_wsgi (pid=1581): Target WSGI script '/var/www/kontext/public/app.py' cannot be loaded as Python module.
[Wed Apr 20 15:41:52 2016] [error] [client 127.0.0.1] mod_wsgi (pid=1581): Exception occurred processing WSGI script '/var/www/kontext/public/app.py'.
[Wed Apr 20 15:41:52 2016] [error] [client 127.0.0.1] Traceback (most recent call last):
[Wed Apr 20 15:41:52 2016] [error] [client 127.0.0.1]   File "/var/www/kontext/public/app.py", line 231, in <module>
[Wed Apr 20 15:41:52 2016] [error] [client 127.0.0.1]     application = App()
[Wed Apr 20 15:41:52 2016] [error] [client 127.0.0.1]   File "/var/www/kontext/public/app.py", line 166, in __init__
[Wed Apr 20 15:41:52 2016] [error] [client 127.0.0.1]     setup_plugins()
[Wed Apr 20 15:41:52 2016] [error] [client 127.0.0.1]   File "/var/www/kontext/public/../lib/initializer.py", line 73, in setup_plugins
[Wed Apr 20 15:41:52 2016] [error] [client 127.0.0.1]     init_plugin('sessions')
[Wed Apr 20 15:41:52 2016] [error] [client 127.0.0.1]   File "/var/www/kontext/public/../lib/initializer.py", line 60, in init_plugin
[Wed Apr 20 15:41:52 2016] [error] [client 127.0.0.1]     raise e
[Wed Apr 20 15:41:52 2016] [error] [client 127.0.0.1] PluginException: Plugin db not installed

**Comment by tomachalek** [comment]
This could have happened due to missing *redis* Python module. Please see your log and check the line preceding the log snipped you have posted here. If you find something like

```
WARNING: Plugin [db] configured but following error occurred: ImportError('No module named redis',)
```
then you have to install the 'redis' Python module:

```
pip install redis
```

**Comment by lylax47** [comment]
I had installed redis-lock and not redis. Got past that now. Thank you! Follow up question (I'm pretty sure I'm having the same issue here): are there any required Python modules for acmeliveattributes? And for future reference, is there any documentation regarding required modules for Kontext plugins?

**Comment by tomachalek** [comment]
### plug-in documentation:

Some information can be found on your wiki (see https://github.com/czcorpus/kontext/wiki/Plug-in-API section *Plug-in objects interfaces*).

### live_attributes plug-in:

This plug-in is optional and I would recommend you to try to set-up KonText without it first as it requires  some additional metadata and configuration tweaking. The name *acmeliveattributes* from the *config.sample.xml* is just a sample name meaning something like "your own implementation of the plug-in". Sorry for inconvenience - the installation process is currently not very user-friendly and *config.sample.xml* has its flaws too (#1074).

To disable the plug-in, just make the respective element empty:

```
<live_attributes></live_attributes>
```

**Comment by tomachalek** [comment]
Python requirements were made more explicit using [requirements.txt](https://pip.pypa.io/en/stable/user_guide/#requirements-files) file.
