### ISSUE TITLE
Editable filters

### ISSUE THREAD

**Issue by stranak** [czcorpus/kontext#1416]
In case this is possible, I didn't find how to do that.

If I make a filter over my search results, or several, I would like to still have the filters editable, i.e. change their type p/n, but also modify the query. Currently I can see the filter on mouse over, but I cannot seem to be able to edit it. Having it editable for instance on clicking the triangle would seem very useful.

![screen shot 2016-11-22 at 23 24 45](https://cloud.githubusercontent.com/assets/371106/20545379/30ec3c12-b10f-11e6-9be0-4ed88a343166.png)

Alternatively (and maybe more intuitively) put the links on the filter titles (that currently remove all filters over this one, i.e. for the last filter clicking the link does nothing) somewhere else and use the filter titles for "edit this filter" links.

**Comment by michkren** [comment]
We have already discussed this in person, so just summing up: you are right, it would be nice to have this functionality and it should also be not too complicated to implement. We will think about assigning it a higher priority, and you are also welcome to contribute to the code (in this case, just let us know in advance, please).

**Comment by tomachalek** [comment]
The upcoming release of KonText (= version 0.10.x) contains a fully editable query "pipeline" which is a query followed by _0..n_ operations from the set _{filter, sorting, random sample}_.

![k010qu](https://cloud.githubusercontent.com/assets/439098/24363788/1bab1c92-1311-11e7-9841-5962d66a393e.jpg)
