### ISSUE TITLE
export with references/meta-information containing commas

### ISSUE THREAD

**Issue by otichy** [czcorpus/kontext#1578]
In all currently available export formats, individual references/meta-information are always delimited by commas. This causes problems if the references themselves contain commas.
Possible solutions:
1, (optionally) enclose values (by quotation marks)
2, user can set a different delimiter
3, (at export?) replace commas in references by something else

**Comment by tomachalek** [comment]
Sorry for such a late response.

In the current version of KonText, multiple "references" values are represented as single strings which makes any further processing unreliable (as the values themselves may contain the separator character). Fortunately, Manatee API provides a method to obtain the data as arrays which makes the mentioned export improvement possible.

**Comment by otichy** [comment]
That sounds great, thanks!

**Comment by tomachalek** [comment]
It should work by now.
