### ISSUE TITLE
Struggeling with installation: Plugin issueReporting

### ISSUE THREAD

**Issue by PeterGilles** [czcorpus/kontext#1932]
Dear all,
I am struggeling with the installation of konText. So far, my config.xml seems to be OK. When running (with sudo) 'npm install; grunt production', I am getting the following error:

> Running "requirejs:production" (requirejs) task
> Error: ENOENT: no such file or directory, open '/home/administrator/kontext/public/files/js/min/plugins/issueReporting/init.js'
> In module tree:
>     pages/coll
>       pages/document
> 
> { Error: Error: ENOENT: no such file or directory, open '/home/administrator/kontext/public/files/js/min/plugins/issueReporting/init.js'
> In module tree:
>     pages/coll
>       pages/document

In the plugin directory I have no 'issueReporting', but there is a 'defaultIssueReporting', though. Thanks for you help!
Peter

**Comment by tomachalek** [comment]
Please update your *config.xml* by adding an element *issue_reporting* as a child of *plugins*. Each plug-in has to have an entry in *config.xml* even if it is not in use (the element has no children in such case - see the example below). The *issue_reporting* has been added recently (few days ago) so it's possible that your *config.xml* got outdated.

```xml
<kontext>
...
  <plugins>
    ...
    <issue_reporting />
   </plugins>
  ...
</kontext>
```

Sorry for the inconvenience, we are working hard to make the next stable release ready ASAP but there is still some work to do.
