### ISSUE TITLE
KeyValueStorage interface - make this compatible with Lindat extensions.

### ISSUE THREAD

**Issue by tomachalek** [czcorpus/kontext#1943]
The problem has two parts:

## Data access methods

In this case I would just adopt the methods (`incr`, `hash_set_map`) just like we do if we need new ones.

## Allowing multiple databases (or even instances) for KonText

The Lindat solution uses a special implementation `RedisDbManager` which implements `KeyValueStorage` along with a special method `get_instance([plugin ID])`. Based on KonText configuration, this allows specifying a different databases for different plug-ins (e.g. KonText uses db *1* but for the *auth* plug-in, *2* is used).

My proposal is based on assumption that there will be no key collisions even across the databases (or 'shards' as used by Lindat plug-in). Let's add the method `get_instance([plugin ID])` to the KeyValueStorage interface with default implementation:

```python
class KeyValueStorage(object):
    # ...
    get_instance(plugins._ID):
      return self
   # ...
```

**Comment by vidiecan** [comment]
Yes, this would work.

**Comment by tomachalek** [comment]
@petrduda  So the extended KeyValueStorage interface should contain these new methods:

* `hash_set_map(self, key, mapping)`
* `incr(self, name, amount=1)`
* `create_instance(plugin_id)`

For more information please see https://github.com/ufal/lindat-kontext/blob/kontext-dev/lib/plugins/redis_db.py
