### ISSUE TITLE
New plug-in token_detail

### ISSUE THREAD

**Issue by tomachalek** [czcorpus/kontext#1944]
We want a general enough solution to cover #404 and possibly other similar requests.

## Scenario

1.  user clicks (or hovers) a token
2. data is loaded via AJAX from KonText (where KonText may ask an external service for the data)
3. a popup-box opens (or a side-bar as mentioned in #404)

## Problems
(numbers map the "scenario" section)

### 1)

I would prefer click over hovering as otherwise just moving mouse over the concordance area view would trigger a (possibly annoying) set of events causing blinking boxes here and there. Adding a delay before the action is triggered can partially solve this but in such case user must deliberately keep mouse  over the item for some time to initialize the loading (nothing for impatient users).

**[UPDATE]** Also, the mouseover is already used by KonText core to display additional selected positional attributes (e.g. *lemma*, *tag* along with directly displayed *word*).

On the other hand, clicking can be a problem in case of KWIC tokens where the onClick event is already in use as it opens the KWIC detail at the bottom of the page.

### 3)

Although a side-bar would be a nice feature with a broader use I would prefer a solution based on currently available widgets. Maybe the best way would be to reuse the existing KWIC detail window because this solves also the problem of clicking on KWIC:

a) user clicks a non-KWIC token - a blue box appears at the bottom of the page (the same as the one used for KWIC detail) with dynamically loaded additional info (e.g. a dictionary entry).

b) users clicks a KWIC token - the very same box appears with both - the dictionary entry and with the kwic detail.

**Comment by tomachalek** [comment]
## notes

### backend(s)

The plug-in should probably support multiple search backends at the same time to allow obtaining information from more than one source. In fact, the backends would be the part where most the customization would happen as the plug-in itself would be just kind of a wrapper.

Possible general backends: URL loader, filesystem loader, database loader. The *config.xml* would contain just paths to backend configurations to reduce configuration tree depth. A similar solution can be already found in case of custom menu items configuration. The values are loaded only on webserver worker start so there is no significant overhead.

```xml
<plugins>
    <token_detail>
        <module>default_token_detail</module>
        <js_module>defaultTokenDetail</js_module>
        <backends>
            <backend>
                <conf>/var/www/kontext/conf/backend1.json</conf>
                <conf>/var/www/kontext/conf/backend2.json</conf>
            </backend>
        </backends>
    </token_detail>
    ...
</plugins>
```

An example of backend configuration:

```json
{
    "module": "url_loader",
    "path": "http://localhost:8080/a_dictionary"
}
```

### args

We must decide which values we are going to send as part of the request. *Lemma* comes to mind, but there are possibly other values too? (e.g. to reduce ambiguity?).

**Comment by stranak** [comment]
- I do like the **option 3)** best, at least for now, without major UI changes.
- **Definitely a list** of sources / dictionaries. See the first screenshot in #404 , it makes sense.
- **args:** just form or lemma should work. Adding POS (UPOS) if it is in data might make sense too, but these arguments must be optional
    - some corpora may not have this analysis and dictionary lookup should still work
    - some dictionaries might only support very simple search

**Comment by tomachalek** [comment]
Our master version provides two new plug-ins: *token_connect* and *kwic_connect*. The plug-ins share configuration and backend classes as they are quite similar on a basic level (looking somewhere for data identified by provided word/lemma/pos).

## kwic_connect

kwic_connect plugin provides automatic info loading based on currently searched kwic

![image](https://user-images.githubusercontent.com/439098/38253852-03784764-3758-11e8-904e-e32023f9b830.png)

## token_connect (formerly 'token_detail')

token_connect provides a way how to attach an external information to any token when clicked on.

![image](https://user-images.githubusercontent.com/439098/38254021-6eef2e68-3758-11e8-8a82-46b8a925dca1.png)

**Comment by tomachalek** [comment]
We have a working beta-version now. Any future problems/suggestions should be solved in separate issues.
