### ISSUE TITLE
conc_persistence3 - create a helper script for splitting of an existing archive

### ISSUE THREAD

**Issue by tomachalek** [czcorpus/kontext#1994]
The script should be able to load KonText `config.xml` (it is ok to hardcode the path as a derived one from the script path - something like `os.path.join(os.path.dirname(__file__), '..', '..', '..', 'conf', 'config.xml')` ).

The only command line arg should be the source database path:

```
python lib/plugins/ucnk_conc_persistence3/scripts/importarch.py /path/to/src.db
```

Please note that currently there is no way how to provide initialized plug-ins for these command line scripts which means you have to initialize them  manually in case you need them.

**Comment by petrduda** [comment]
The number of resulting archives will then have to be based on the archive size limit config value. In #1885, it seemed the number of files to split the source archive could be specified by admin. Or should the script accept an optional parameter, e.g. --splitinto xx ?
