### ISSUE TITLE
overlap/sub-hits filter

### ISSUE THREAD

**Issue by Ansa211** [czcorpus/kontext#2112]
Bonito 3.33 introduced a feature called "overlaps/sub-hits filter"; according to [SketchEngine's documentation](https://www.sketchengine.co.uk/user-guide/user-manual/concordance-introduction/working-with-concordance-results/#filter), it works as follows:

If the searched structure contains another such structure inside, only the outer structure will be displayed as result. For example, CQL searching for "J.*"{1,3}"N.*"(default attribute: tag), i.e. a noun preceded by 1 to 3 adjectives, will find big black dog. This phrase contains another phrase which matches the search criteria – black dog. Two concordance lines will be displayed. When the filter is applied, only the former phrase will be displayed.

This is a useful function and it would be nice to have it in KonText, too.

Example:
[search  for the word "lodích" preceded by 1 to 3 adjectives](https://the.sketchengine.co.uk/corpus/first?corpname=preloaded%2Fcskell_2_2&reload=&iquery=&queryselector=cqlrow&lemma=&lpos=&phrase=&word=&wpos=&char=&cql=%5Btag%3D%22k2.*%22%5D%7B1%2C3%7D+%22lod%C3%ADch%22&default_attr=word&fc_lemword_window_type=both&fc_lemword_wsize=5&fc_lemword=&fc_lemword_type=all&fc_pos_window_type=both&fc_pos_wsize=5&fc_pos_type=all&fsca_s.gdex_score=)    notice the overlapping examples on first three lines
[the same query after applying Filter > Sub-hits](https://the.sketchengine.co.uk/corpus/viewattrsx?q=aword%2C%5Btag%3D%22k2.*%22%5D%7B1%2C3%7D+%22lod%C3%ADch%22&q=D&corpname=preloaded%2Fcskell_2_2&attrs=word%2Ctag&ctxattrs=word&structs=g&refs=%3Ds.gdex_score&gdexconf=&attr_tooltip=nott&fromp=1&setattrs=word&allpos=kw&attr_tooltip=nott&setstructs=g&setrefs=%3Ds.gdex_score&refs_up=0&pagesize=20&newctxsize=40&gdex_enabled=0&show_gdex_scores=0&gdexcnt=100&icon_copy=0&multiple_copy=0&use_noflash=0&select_lines=0&line_numbers=0&shorten_refs=0&shorten_refs=1&tbl_template=none)

**Comment by tomachalek** [comment]
I'll discuss this with @michkren and as long as the function is available in the free version of Manatee, I believe it's worth implementing it.

**Comment by tomachalek** [comment]
Working on it...
