### ISSUE TITLE
Shorten long references

### ISSUE THREAD

**Issue by msklvsk** [czcorpus/kontext#2131]
It would be great to be able to trim long references at certain width and expand them on hover.
This is supported in bonito since 3.29 and I bet users would love this feature as much as I do.

**Comment by msklvsk** [comment]
I was thinking about replicating bonito functionality.
- The whole references column is truncated, not individual references.
- A reference row gets expanded on hover instantly, into the corresponding row.

(Which is a whole another experience.)

![references](https://user-images.githubusercontent.com/473012/34707877-a0f47d78-f518-11e7-940d-83372c21e8b1.gif)

**Comment by tomachalek** [comment]
OK, I'll discuss this will my colleagues whether they like the idea.
