### ISSUE TITLE
Kontext up and running, word lists ok but query gets stuck

### ISSUE THREAD

**Issue by hrmJ** [czcorpus/kontext#2334]
Hi, 

I Installed Kontext in an lxc container (ubuntu 16.04; host running ubuntu 17.10) as adviced in the documentation. I was, at first, facing a similar issue as PeterGilles in #1937 in that the susanne sample corpus wasn't in the list of available corpora -- this was fixed by modifying users.json of the default_auth plugin and now I am able to use the word lists functionality. However, when I try to query the test corpus, kontext gets stuck: 

![image](https://user-images.githubusercontent.com/11331344/39290752-5918d632-4939-11e8-9976-524dceed62d3.png)

The debugger doesn't show anything related to this, the last line is:

`2018-04-26 07:03:35,421 [werkzeug] INFO: 10.0.3.1 - - [26/Apr/2018 07:03:35] "GET /first_form?corpname=susanne&align= HTTP/1.1" 200 -`                                                                                

(Also, there seems to be no CPU activity related to kontext other than just `app.py` and `redis-server`)

Any ideas?

**Comment by tomachalek** [comment]
Is it possible that you have `multiprocessing` set as a backend for concordance computing? 
(i.e. in config.xml, `<global><calc_backend>multiprocessing</calc_backend>...`). I've found an error there which I'm going to fix (hopefully today)

**Comment by hrmJ** [comment]
I'm using the defaults from config.sample.xml , so I have:

`<calc_backend conf="/opt/kontext/conf/celeryconfig.py">celery</calc_backend>`

I tried with `multiprocessing`, and  the query didn't get stuck (although it returned no results), so I guess it's an issue with Celery.  Where should I look for the log?

**Comment by tomachalek** [comment]
If you use _systemd_ to handle Celery service, then look at the `/etc/systemd/system/[your_celery_conf_file]` and there you'll find something like `EnvironmentFile=[some file]` (probably _/etc/conf.d/celery_) Open the file and search for the 
`CELERYD_LOG_FILE` variable.

**Comment by hrmJ** [comment]
OK, found the log and it turned out that *www-data* didn't have access rights to `var/local/corpora/cache/` . Fixed the permissions and everything seems to work now. Thanks a lot!
