### ISSUE TITLE
button for limiting filter to "within <s/>"

### ISSUE THREAD

**Issue by Ansa211** [czcorpus/kontext#2358]
When using the filtering options, it would usually be more sensible if the filter could be limited to the tokens in which the given window (e.g. from -5 to 5 tokens) intersects with the sentence containing the KWIC. In other words, I imagine that the following line in the `Apply a “filter” operation` pop-up
 **Search span:** from: ___ to: ___, Include KWIC [ ]
could be extended to
 **Search span:** from: ___ to: ___ (within `<s/>` containing the KWIC [ ], include KWIC [ ])

The `<s/>` attribute should not be hardcoded, but the attribute which is used by the `View > KWIC/Sentence` option should be used (e.g. in the ortofon corpus, there is no `<s/>`, but it seems that `<sp/>` is used as the "sentence" segment).

**Comment by tomachalek** [comment]
We've discussed this and we are not sure whether Manatee supports such a function. So unless you have additional information on how this can be done in Manatee, we're probably out of luck here.
