### ISSUE TITLE
Frendlier error, access denied

### ISSUE THREAD

**Issue by kosarko** [czcorpus/kontext#2413]
When you click the kwic, this blue box with more context appears. There's a link `Display whole document`. If you click that and you are not logged in; you get just "error,Access forbidden" message. Would it be possible to add more details, like "please login" to the message?

@stranak @ansa211

**Comment by tomachalek** [comment]
You mean that "Access forbidden" should always contain the "login" button or is it only about the "Display whole document" functionality?

**Comment by Ansa211** [comment]
We mean that, as users, we did not infer that "Access forbidden" actually means "You have to be logged in in order to access this functionality".

**Comment by tomachalek** [comment]
OK, I get it.
