### ISSUE TITLE
corpus selection

### ISSUE THREAD

**Issue by Ansa211** [czcorpus/kontext#2453]
Pozorování k tomu, jak se ÚČNK instance chová, když si na vstupní stránce https://kontext.korpus.cz/first_form rozkliknu "Corpus -> All corpora":

Co funguje hezky:
- při výběru korpusů si lze vybrat tag "současná verze" nebo "starší verze" a kombinovat ho s ostatními tagy nebo s ručním hledáním v názvech korpusů a podkorpusů

Co mi připadá nedořešené:
- řazení v našeptávaném seznamu je asi abecední, ale zas ne všude (např. pod volbou "řada SYN" vidím "syn v6, syn v5, syn v4, syn v3, syn_ufal, syn2000, syn2005, syn2006pub, ..." ta čísla jdou napřed dolů a pak naopak nahoru???), někde se zdá, že ani nemá zabudované předřazení současných verzí na horní konec seznamu, takže například pod tagem Oral vidím "oral v1" (největší a tedy asi nejnovější), ale pak od nejstaršího "oral 2006, oral 2008, oral 2013"; podobně pod tagem synchronní vidím různě velké verze podkorpusů korpusu Araneum, ale dostanu se jen k ruštině a těžko uhodnout, jaké další jazyky - nebo jaké další sady korpusů - tanto tag také mají, a pod tagem "čeština" sice vidím dvě různé verze korpusu diakorp (které při přidání podmínky na tag "současná verze" obě zmizí), ale díky abecednímu řazení to končí u "schola2010", a žádný z korpusů řady SYN (což by měla být vlajková loď české sady) se do nabídky nedostane

**Comment by tomachalek** [comment]
Na začátek jen informaci, že řazení korpusů je manuální s tím, že abecedně jsou řazeny pomyslné skupiny (skupina == různé verze jednoho korpusu, např. SYN20XX, SYN_vX, ORAL..., ostatní korpusy lze chápat jako jednoprvkové skupiny - orwell, speeches, jerome atd.). V rámci těchto skupin pak jsou položky řazeny tak, aby nejnovější verze byly jako první. Faktem je, že stávající uspořádání může obsahovat chyby či sporná místa - proberu s kolegy.

**Comment by michkren** [comment]
Problém bych rozdělil na dva:
- Uživatel nepozná, jestli vidí kompletní nebo nekompletní seznam. Tady jsme se shodli na tom, že je potřeba to zvýraznit, protože některé seznamy zůstanou vždycky moc dlouhé. Konkrétně navrhujeme vylepšit zobrazování tak, aby se v případě nekompletního seznamu viditelně zobrazilo něco jako "your selection gives too many results, please specify additional filters" a přitom se zvýraznily další možnosti (možnost zvolení dalších labelů a možnost omezit množinu korpusů napsáním části názvu nebo popisu korpusu).
- Pořadí pomyslných skupin (SYN, ORAL atd.), řazení v rámci nich a případně také výběr/vymezení některých labelů. Shodujeme se na tom, že je potřeba s tím něco udělat, ale ne už tak úplně, jaké řešení je nejlepší :)  Budeme o tom ještě diskutovat interně, první bod ale bude potřeba implementovat určitě.
