### ISSUE TITLE
right-to-left script causing havoc in the top bar

### ISSUE THREAD

**Issue by Ansa211** [czcorpus/kontext#2489]
![arabic](https://user-images.githubusercontent.com/1833866/43900119-2aefaf80-9be4-11e8-917a-f41ecb7dfee5.png)

This part is broken:
Query: some-arabic-text (32 hits)
Notice a funny thing - the beginning bracket is turned into what would be a beginning bracket in right-to-left text.

The same happens also on Lindat.

**Comment by Ansa211** [comment]
More issues with right-to-left texts:

The __display of attributes in concordances__ when right-to-left and left-to-right text is mixed:
![concordance_lines](https://user-images.githubusercontent.com/1833866/43905332-2abbe09e-9bf1-11e8-9fae-8804def92ad9.png)

The cursor in the __query input field__ is usually situated at the wrong end of the field (i.e., at the left end when it is at the beginning of the string and at the right end when it is at its end)... however, that happens with almost all language apps that I have seen, so probably it is impossible to completely solve that issue.

**Comment by tomachalek** [comment]
The top bar issue can be solved. But the concordance lines would be much harder to fix (CSS tweaking is not enough there). So I'm going to add a warning  to "corpus specific settings" -> "structures" in case a right to left text corpus is used.

**Comment by Ansa211** [comment]
The warning in options comes out as `options__rtl_text_warning` - I suppose some variable expansion goes wrong.
