### ISSUE TITLE
a plugin box lurking behind another plugin box

### ISSUE THREAD

**Issue by Ansa211** [czcorpus/kontext#2537]
Steps to reproduce:

Go to https://kontext.korpus.cz/view?ctxattrs=word&attr_vmode=visible&pagesize=100&refs=%3Ddoc.id&q=~6nvxZOfsUk&viewmode=kwic&attrs=word&corpname=oral_v1&attr_allpos=kw

Click on the structure id 06A138N in the left column, then click on the word "pojede" in the KWIC:

![plugin_behind_another](https://user-images.githubusercontent.com/1833866/44669623-a8a71e00-aa20-11e8-8ab9-c39eb747d299.png)

Now click on "Default view" at the top of the plugin that is only partially visible. It seems that it has disappeared comletely. But when you close the remaining plugin, it turns out that the "context view" has not disappeared, it just was so small that it was completely hidden by the larger box of the "information box".

**Comment by tomachalek** [comment]
Please note that this change will not apply for the production version of CNC's KonText until version 0.12 is officially released (2nd half of September).
