### ISSUE TITLE
not enough space with display attributes directly in text for all the tokens combined with Sentence View

### ISSUE THREAD

**Issue by Ansa211** [czcorpus/kontext#2619]
Used settings:
View -> KWIC/Sentence
View -> Corpus Specific Settings -> select some attribute and Viewing options "Directly in text" and "for each token"

Result: a space is missing to the left of the KWIC.

![spacing](https://user-images.githubusercontent.com/1833866/47102547-54106a00-d23d-11e8-9890-4cb9f4591675.png)

Settings as above except for selecting "for KWIC tokens only": there is not enough space to the left of KWIC when it is preceded by a displayed structural attribute.

![spacing1](https://user-images.githubusercontent.com/1833866/47102809-f6c8e880-d23d-11e8-9758-29ef7c33a877.png)

The issue can be reproduced on lindat-kontext.

**Comment by tomachalek** [comment]
Here a different screenshot from another user:
![Screen Shot 2020-04-07 at 21 27 30](https://user-images.githubusercontent.com/439098/79207078-830e9880-7e40-11ea-9e83-80fe23f41f8e.png)

**Comment by tomachalek** [comment]
Fixed in #3012
