### ISSUE TITLE
no space between KWIC words

### ISSUE THREAD

**Issue by Ansa211** [czcorpus/kontext#2778]
![whitespace](https://user-images.githubusercontent.com/1833866/54397498-fc284300-46b6-11e9-8260-2b2da8487ba4.png)

It's [this query](https://kontext.korpus.cz/view?q=~MiVpup3fFRfo)

Corpus-specific settings for my user: display word, lemma, tag *only on token mouseover*

**Comment by tomachalek** [comment]
Thank you for the report and sorry for such a late response.
