### ISSUE TITLE
Put limit on max. items per page for concordance, freqs, collocs, wordlists

### ISSUE THREAD

**Issue by tomachalek** [czcorpus/kontext#2791]

**Comment by michkren** [comment]
My suggestion is to set all the limits for page size to 1000 items (or perhaps 999?). What about the KWIC context size limit? Perhaps it would make sense to limit this as well to say 100 (or 99?) positions?
BTW: while playing around with the limits (and setting them very high), the browser has caused my ubuntu to crash, so this may be a serious issue.
