### ISSUE TITLE
Available corpora: add a "favourite" keyword

### ISSUE THREAD

**Issue by Ansa211** [czcorpus/kontext#2803]
It is possible to access the list of available corpora from the first_form ("Enter new query") interface:

![favourite1](https://user-images.githubusercontent.com/1833866/59917565-8e608580-9422-11e9-8a13-90152a6efd25.jpeg)

--
Maybe it would be meaningful to also filter for favourites on the "Available corpora" pages:
![favourite2](https://user-images.githubusercontent.com/1833866/59917567-8ef91c00-9422-11e9-83ea-ff1ab33943f9.jpeg)

**Comment by tomachalek** [comment]
Core "corparch" plug-ins (default_corparch, rdbms_corparch, ucnk_corparch2) now provide the functionality. Porting this to "lindat_corparch2" plug-in should be quite easy but the details depend on how the *lindat_corparch2* is derived from "default_corparch" (i.e. if it reuses most of the functionality  e.g. by extending involved classes).

**Comment by Ansa211** [comment]
If that means that the issue is solved on the ÚČNK instance, it can be closed here - I created a separate issue in the lindat-kontext issue tracker.

**Comment by tomachalek** [comment]
Yes, it's solved within the "ucnk" and "default" (which neither CNC nor Lindat uses) plug-in versions. Closing the issue...
