### ISSUE TITLE
unable to make a subcorpus public

### ISSUE THREAD

**Issue by Ansa211** [czcorpus/kontext#2865]
When I try to make one of my subcorpora public, I get an error pop-up saying:

"error,Chyba při zpracování požadavku. Opakujte prosím akci později nebo kontaktujte technickou podporu."

**Comment by tomachalek** [comment]
@Ansa211 Can you please confirm it works for you at https://kontext.korpus.cz ?

**Comment by Ansa211** [comment]
It still does not work for me :-(

**Comment by tomachalek** [comment]
Marking as stale. In the meantime, the subcorpora subsystem was rewritten so it should not be relevant any more.
