### ISSUE TITLE
Python 3 roadmap?

### ISSUE THREAD

**Issue by lenoch** [czcorpus/kontext#2890]
`​manatee-open-2.167.8` was [released](https://nlp.fi.muni.cz/trac/noske/wiki/Downloads) on 1 Nov 2019, now supporting Python 3 alongside Python 2. (The dual compatibility is apparent if you compare the `api` directory against v2.158.8, or see changes in build scripts. The official changelog is still silent about this release.)

Is there a road map to migrate KonText to Python 3, before Python 2 goes into unsupported mode in 2020?

I believe the first step should be painless: first upgrade to the new `manatee-open` while still using Python 2.7 (there should be no regression).

Only then figure out how to upgrade the codebase to Python 3 (`2to3` might help a little). I believe that while supporting both versions makes sense for `manatee-open`, KonText should not support both versions at one time but switch to Python 3 exclusively — unless the conversion should take too long or too many steps and would have to be done gradually.

**Comment by tomachalek** [comment]
We've been already discussing the issue at the CNC mainly due to the Python 2 EOL and we've agreed on the need for upgrade to Python 3. But there is no concrete roadmap yet. I am quite sure though that we won't be able to resolve this till the end of the year 2019.

**Comment by tomachalek** [comment]
Please check https://github.com/czcorpus/kontext/issues/2892 for future updates.
