### ISSUE TITLE
How to transfer my file(.txt) to a corpus for the Manatee search engine?

### ISSUE THREAD

**Issue by dvzhang** [czcorpus/kontext#2915]
If i have a raw corpus in txt format, how can i transform this corpus to manatee format from scratch?

**Comment by tomachalek** [comment]
Hello @dvzhang , sorry for such a late response. To be able to import your corpus, you have to convert your TXT file into a so called [vertical file](https://www.sketchengine.eu/my_keywords/vertical/) where each token takes a single line. Without any additional information (i.e. lemmatization, pos tagging, structural information etc.) the file would look like this:
```
This
is
the
first
sentence
.
This
is
the
second
one
.
```
Also, you have to create a [corpus configuration file](https://www.sketchengine.eu/documentation/the-corpus-configuration-file/). Once you have one, you can use Manatee's `encodevert` tool to compile your vertical file. Enabling the corpus within KonText should be described elsewhere in this repository.  For more Manatee-related information please refer to [https://www.sketchengine.eu/documentation/](https://www.sketchengine.eu/documentation/).
