### ISSUE TITLE
Allow configuring a default (virtual) keyboard for a corpus

### ISSUE THREAD

**Issue by tomachalek** [czcorpus/kontext#2957]
KonText query input contains a small widget "keyboard" which allows entering misc. characters possibly not present on user's system. We would like KonText to be able to set a concrete keyboard layout as a default one (i.e. a respective select element should be pre-set to this value).

The setting should be a part of corpus configuration, which means at least `default_corparch`, `rdbms_corparch` and `ucnk_corparch2` should be updated and other `corparch` plug-ins (`lindat_corparch2`) should be at least compatible.

Involved Python classes: `lib/plugins/abstract/corpora/CorpusMetadata` (use a new attribute named e.g. `default_virt_keyboard`).

In case of default_corparch (and also lindat_corparch2), XML corplist config file should be updated like this:
```xml
<corpus ... default_virt_keyboard="Czech phon./dial." ... />
```
In case of rdbms_corparch, please see table `kontext_corpus` and add the new attribute.

In case of ucnk_corparch2, please see table `corpora` and add the new attribute.

Notes:
- list of keyboard layouts: `public/files/js/kb-layouts.json`,
  - value used there as ID: `name` (e.g. `Czech phon./dial.`)
- keyboard js model: `js/models/query/virtualKeyboard.ts`

**Comment by mzimandl** [comment]
Added in #2959
