### ISSUE TITLE
Styling of structures shown in concordance

### ISSUE THREAD

**Issue by dlukes** [czcorpus/kontext#3048]
Previously, structures displayed in concordance lines were styled differently from the main text to help distinguish them (green fg color, maybe some other properties?); they are now styled the same as the surrounding text.

![image](https://user-images.githubusercontent.com/2734517/82070354-e8220c00-96d4-11ea-8cd4-bc3ed8c7118d.png)

**Comment by tomachalek** [comment]
Sorry for forgetting this - the issue has been already resolved.
