### ISSUE TITLE
not seing new corpus

### ISSUE THREAD

**Issue by cepriy** [czcorpus/kontext#3101]
Having compiled a new corpus successfully, having added the new corpus name to /opt/kontext/conf/corplist.xml, I restart gunicorn.service:

    `systemctl` restart `gunicorn.service`

But I still can't see the new corpus, when I launch KonText by its IP, I can only see Susan corps. What else should I do to force KonText to see the newly compiled corpus?

**Comment by mzimandl** [comment]
Try to update user access rights for new corpus
https://github.com/czcorpus/kontext/blob/master/doc/INSTALL.md#update-access-rights

**Comment by Ceprey2** [comment]
Thanks!
I've tried to update user access

`python lib/plugins/default_auth/scripts/usercorp.py 0 add ParallKorpUkrChartUN`

but, unfortunately, I'm getting an error:
`  File "lib/plugins/default_auth/scripts/usercorp.py", line 22, in <module>
    import autoconf
  File "/opt/kontext/scripts/autoconf.py", line 47, in <module>
    import settings
  File "/opt/kontext/lib/settings.py", line 34
    _conf: Dict[str, Any] = {}
         ^
I didn't add new users, using only those with ids 0 and 1

**Comment by mzimandl** [comment]
Aha! It seems we have to update our manual :)
First the script uses Python 3. And second user ids start from 1 (1 - anonymous user, 2 - kontext user after fresh install).
So something like
`python3 lib/plugins/default_auth/scripts/usercorp.py 1 add ParallKorpUkrChartUN`
should work

**Comment by mzimandl** [comment]
Prepared a fix #3108 for that for the `py2to3` branch

**Comment by Ceprey2** [comment]
Thanks a lot! User updating worked for me. But, unfortunately, I still can't see bur Susanne corpus, once updated corplist.xml as well as access rights.
