### ISSUE TITLE
Return to a query - restore also the calendar component properly

### ISSUE THREAD

**Issue by tomachalek** [czcorpus/kontext#3435]
This will allow proper data serialization (in a sense - redundant serialization) - otherwise we need to transform a datetime regexp to a range :scream:

**Comment by tomachalek** [comment]
Update - it seems that currently, none of the value selection box type is restored (i.e. checkbox based ones, raw input with auto-complete, calendar).

**Comment by mzimandl** [comment]
Everything seems to be working fine after #3515, #3517 and #3521
