### ISSUE TITLE
Word list alphabetical ordering

### ISSUE THREAD

**Issue by tomachalek** [czcorpus/kontext#345]
The ordering can be described as uppercase first, accented last (ANSI C ? ).

Replication:
1) Select "Seznam slov", corpus "diakorp" and "._ň._" as the pattern to keep the list small
2) click on "word" in the column heading to re-sort alphabetically
3) the list now lookss like this:

Aspoň  8
Baňka  13
Baňky  13
Báseň 10
Břeňku    10
KVň    9
Koňové    6
Kuoň   15
Kůň   71
Levoň  20
Naplň  6
Oheň   32
Plzeň  22
Plzeňští 5
Povstaň    6
Proňežto  159
Píseň 13
Staň   6
Učiň  30
Vstaň  32
Vstaňte    16
Vídeň 6
Vídeňské 8
Zapomeňte  5
Zároveň   12
Zůstaň    13
alespoň    10
aspoň  275
baňkami    20
baňku  12
baňky  32
braň   10
báseň 39
bázeň 35
chraň  6
daň    18
dlaň   14

...

zaň    65
zbraň  18
zbraňoval  11
zbraňuje   13
zbraňují  7
změňuje   6
zároveň   83
zůstaň    11
Štíropeň 5
Ščíropeň    18
šiliňkuov 8
šňůry    9
žeň   24
žížeň   19
Čiň   5
čerň  5
čiň   150
čiňte 23
ňader  6
ňadra  11
ňadrech    5
ňeho   161
ňehož 11
ňehožto   28
ňem    171
ňemu   299
ňemuž 24
ňemužto   40
ňemž  43
ňemžto    75
ňežto 25
ňádra 6

**Comment by Ansa211** [comment]
The weird sorting is still applied, e.g. in this sorted sample, "Najdi" < "bude" < "bát" < "chce" < "dají"
https://kontext.korpus.cz/view?q=~qpA65ovlsePl
(It would be extra nice if Czech sorting rules for "ch" would also be applied.)
