### ISSUE TITLE
[master] Spurious syntax error in basic query with regular expressions

### ISSUE THREAD

**Issue by dlukes** [czcorpus/kontext#3456]
Basic queries in the upcoming version of KonText support enabling regular expressions, but when I start typing `(?i)` (the case insensitive PCRE modifier), KonText currently displays an error (even though the query subsequently evaluates correctly): `regexopt: at position 1: syntax error, unexpected $end`.

**Comment by tomachalek** [comment]
We've made some related fixes/updates. Can you please review the issue?

**Comment by dlukes** [comment]
LGTM, thanks!
