### ISSUE TITLE
implement KonText set-up validator

### ISSUE THREAD

**Issue by tomachalek** [czcorpus/kontext#35]
What should be checked:

1. XML validity
1. references (i.e. a string value referring to an element with specific attribute)
1. basic plug-ins configuration (especially whether there are required modules present)
1. paths - whether they exist and whether the web server has proper access rights

**Comment by lylax47** [comment]
This may not be the place for such a question, and if so please feel free to delete it. I'm currently trying to use Kontext with the Russian National Corpus, but running into a problem with initializing the locking module. I'm thinking there may be a problem with my config.xml file, but I'm not entirely sure. Redis-lock is installed. Here's a copy of the error in apache2 logs:

[Sun Apr 17 15:56:40 2016] [notice] caught SIGTERM, shutting down
[Sun Apr 17 15:56:41 2016] [notice] Apache/2.2.22 (Ubuntu) mod_wsgi/3.3 Python/2.7.3 configured -- resuming normal operations
[Sun Apr 17 15:56:44 2016] [error] [client 127.0.0.1] mod_wsgi (pid=21912): Target WSGI script '/var/www/kontext/public/app.py' cannot be loaded as Python module.
[Sun Apr 17 15:56:44 2016] [error] [client 127.0.0.1] mod_wsgi (pid=21912): Exception occurred processing WSGI script '/var/www/kontext/public/app.py'.
[Sun Apr 17 15:56:44 2016] [error] [client 127.0.0.1] Traceback (most recent call last):
[Sun Apr 17 15:56:44 2016] [error] [client 127.0.0.1]   File "/var/www/kontext/public/app.py", line 231, in <module>
[Sun Apr 17 15:56:44 2016] [error] [client 127.0.0.1]     application = App()
[Sun Apr 17 15:56:44 2016] [error] [client 127.0.0.1]   File "/var/www/kontext/public/app.py", line 166, in __init__
[Sun Apr 17 15:56:44 2016] [error] [client 127.0.0.1]     setup_plugins()
[Sun Apr 17 15:56:44 2016] [error] [client 127.0.0.1]   File "/var/www/kontext/public/../lib/initializer.py", line 77, in setup_plugins
[Sun Apr 17 15:56:44 2016] [error] [client 127.0.0.1]     init_plugin('locking')
[Sun Apr 17 15:56:44 2016] [error] [client 127.0.0.1]   File "/var/www/kontext/public/../lib/initializer.py", line 60, in init_plugin
[Sun Apr 17 15:56:44 2016] [error] [client 127.0.0.1]     raise e
[Sun Apr 17 15:56:44 2016] [error] [client 127.0.0.1] PluginDependencyException: redis_locking requires a key-value storage with "setnx" and "getset" methods

**Comment by tomachalek** [comment]
Please check you configuration of *db* plug-in. In KonText, some plug-ins (including the *locking* one) require an application-wide database adapter called *db* plug-in. In case you want to use the default locking  (= *redis_locking*) you have to install [Redis](http://redis.io/) database and configure *redis_db* as your *db* plug-in in KonText:

```xml
<plugins>
...
  <db>redis_db</db>
    <host extension-by="default">your_redis_hostname</host>
    <port extension-by="default">redis_port</port>
    <id extension-by="default">database_numeric_id</id>
  </db>
...
</plugins>
```

The upcoming version of KonText (0.9, currently unfinished in the [master](https://github.com/czcorpus/kontext/tree/master) branch) will drop the requirement for the *locking* plug-in. But even then,  *redis_db* will still be the best choice for a *db* plug-in (unless you have to use some other database for whatever reason).

If you have any other questions/problems regarding KonText installation or configuration please feel free to add a new "issue" and I will try to help you out.
