### ISSUE TITLE
Speech view is broken on first load, metadata never shows up

### ISSUE THREAD

**Issue by dlukes** [czcorpus/kontext#3647]
This is what it looks like:

![image](https://user-images.githubusercontent.com/2734517/102688068-88ed2280-41f4-11eb-8ad4-d1ac741b0d44.png)

The text should be split among different speakers. You need to expand the context in order for that to happen and for the speaker labels to appear.

And I can't seem to get the metadata to show up:

![image](https://user-images.githubusercontent.com/2734517/102688108-bdf97500-41f4-11eb-8db0-1db49f0174e8.png)

**Comment by tomachalek** [comment]
Should be ok by now.

**Comment by dlukes** [comment]
Has the fixed been pushed to production? What I'm currently experiencing is that the speech view is fine, but the metadata is still not loading.

**Comment by tomachalek** [comment]
Now it should be completely OK (incl. production installation).

**Comment by dlukes** [comment]
Indeed, thanks a lot!
