### ISSUE TITLE
Ctrl+A followed by Del or Backspace doesn't work as expected in the query form

### ISSUE THREAD

**Issue by dlukes** [czcorpus/kontext#3726]
This sequence of actions should remove the selected text. Instead, pressing Backspace unselects it and jumps to the beginning, and Del deletes only the first character, unselects it and jumps to the end.

Weirdly enough, when the text is selected with the mouse or Shift + arrow keys (instead of Ctrl+A), Del and Backspace work as expected. And Ctrl+A followed by Ctrl+X also works as expected.

**Comment by tomachalek** [comment]
As far as I've been able to understand, in Firefox, a text selection triggered by "CTRL+a" (or Meta+a) does not provide a correct text selection range. I've implemented the function manually for FF. Please note that I cannot test the fix in macOS (as I don't have one) so any macOS-related feedback would be welcome :-)

**Comment by dlukes** [comment]
I tried it out on macOS and seems to work fine, thanks! :)

One tiny nitpick: on macOS, Ctrl+A should technically behave like the Home key (= jump to the beginning of the line), which is what happens in Safari, but in Firefox, it now does the same thing as Cmd+A (= select all). But maybe it's not worth it worrying about separately implementing the Home behavior for Ctrl+A, since the group of people which use KonText on Firefox on macOS and know about the shortcut is probably vanishingly small.

**Comment by dlukes** [comment]
Though AFAICS, Ctrl+E (= End on macOS) works correctly on Firefox, so maybe it's just a matter of disabling an override which makes Ctrl+A select all?
