### ISSUE TITLE
Invalid tagset summary link

### ISSUE THREAD

**Issue by vidiecan** [czcorpus/kontext#398]
1. Tagset summary link in registry/\* takes you to a non-existent page: http://ucnk.ff.cuni.cz/bonito/znacky.php . Replace with https://ufal.mff.cuni.cz/pdt/Morphology_and_Tagging/Doc/hmptagqr.html when relevant
2. When other tagsets are used, find a proper link

**Comment by natalink** [comment]
1. resolved -  links fixed
2. still to do

**Comment by tomachalek** [comment]
Is this still relevant?

**Comment by tomachalek** [comment]
outdated, without response
