### ISSUE TITLE
Features:words only

### ISSUE THREAD

**Issue by vidiecan** [czcorpus/kontext#400]
1. When a corpus is not annotated shall we leave the attribute empty, or add 'words only'/'word forms only'/'no annotation' message?
2. The notion 'Features' will not be very intuitive for me as a linguist, I would rather see something like 'annotation' instead. May be 'Annotation: morphology syntax' or 'Annotation: no' would be better?

**Comment by Ansa211** [comment]
can be closed: I have migrated this question to Lindat issue tracker
