### ISSUE TITLE
Kontext logo link – list of corpora

### ISSUE THREAD

**Issue by stranak** [czcorpus/kontext#416]
In the LINDAT Kontext, change the link on the Kontext logo (serving as "home") from the [first_form](https://lindat.mff.cuni.cz/services/kontext/run.cgi/first_form) to the list of [Available Corpora](https://lindat.mff.cuni.cz/services/kontext/run.cgi/corplist). This is our natural homepage and now it is not intuitively accessible.

If we do this we can remove the list of available corpora from the Help menu.

**Comment by tomachalek** [comment]
I believe we can make this a part of #407. In the description there, a configurable logo is mentioned too. Allowing also to customize logo's URL seems quite natural to me.

The only issue is that in case an administrator wants only a custom logo URL (i.e. no visual changes at all) a *theme* configuration element will still have to be present.

**Comment by stranak** [comment]
Seems perfectly reasonable. I see you have added the confugurable URL there already, so I am closing this as duplicate.

Became part of #407.
