### ISSUE TITLE
Localisation of the type of search

### ISSUE THREAD

**Issue by TomazErjavec** [czcorpus/kontext#4373]
In the "Search in the corpus" window there is the menu item "Recent queries". If you click on it, it also tells you with each remembered query its type ("simple", "iquery", "cql"). However, these types are not localised to Czech (nor, it seems , localisable, at least I can't find them in the localisation json files).
Conversely, in the top-level menu you also have Query/Recent queries, and here the types of search _are_ localised, e.g. "(Jednoduchý dotaz)". So maybe the same localisation strings could be used for both?
Also note that here "iquery" is missing the translation, you just get "()" instead of "(the Czech translation of iquery)"

**Comment by tomachalek** [comment]
Should be fixed in 655d09fbd2f41dba7c6c5ae871f3acf1c163de3b
