### ISSUE TITLE
What's the default user & password of the dockerized app?

### ISSUE THREAD

**Issue by fishfree** [czcorpus/kontext#4451]
After run `docker-compose -f docker-compose.yml -f docker-compose.mysql.yml --env-file .env.mysql up -d`, I can access the interface, but don't know the default admin user and password.

**Comment by tomachalek** [comment]
Unfortunately, there is no web-based administration section in KonText. So to e.g. add users or add corpus access rights to users, a script must be run using command line.

## Adding new user(s)

1. Create a file containing a list of new users. The structure can be seen in the example file `lib/plugins/default_auth/users.sample.json`

2. Run `python3 lib/plugins/default_auth/scripts/import_users.py your_user_file.json`

## Adding access rights to users

1. Run `python3 lib/plugins/default_auth/scripts/usercorp.py` (try the `-h` option for more info)

**Comment by fishfree** [comment]
After running:
```
root@0c3b8f76da5b:/opt/kontext# python3 lib/plugins/default_auth/scripts/import_users.py lib/plugins/default_auth/scripts/users.json
Installed user anonymous
Installed user admin
```
When login, still displayed `Incorrect username or password`.
Then I try to signup a user, it said` A confirmation e-mail has been sent to the address wzzhang@shisu.edu.cn. Please follow the instructions in the e-mail to activate your account.` Where can I set SMTP config?
More documentation, please :-)

**Comment by tomachalek** [comment]
Regarding the SMTP configuration:

```xml
<kontext>
  ...
  <mailing>
      <smtp_server>your.smtp.server</smtp_server>
      <smtp_port>port_number_of_the_server</smtp_port>
      <auth_username>your_username</auth_username>
      <auth_password>your_password</auth_password>
      <use_tls>true</use_tls>
      <sender>some.mail.representing.kontext.app@some_domain</sender>
  </mailing>
  ...
</kontext>
```

I can only agree that the documentation should be upgraded/improved 😇 . I cannot promise anything specific at the moment as we are finishing the upcoming version but hopefully, we will be able to improve the documentation soon.

**Comment by fishfree** [comment]
@tomachalek Thank you, Sir. I can login now. How is going with your improving the documentation? Kontext is so POWERFUL!!! I'd like to use it very much!
