### ISSUE TITLE
How to build voice/acoustic corpus with Kontext?

### ISSUE THREAD

**Issue by fishfree** [czcorpus/kontext#4527]
I noticed here is [a voice corpus.](https://lindat.mff.cuni.cz/services/kontext/view?ctxattrs=word&attr_vmode=mouseover&pagesize=40&refs=%3Ddoc.id&q=~EIduelo7U08x&viewmode=kwic&attrs=word&corpname=airtraffic_en_w&attr_allpos=all) Wonder how to make it? Too few documentations. :-(

**Comment by tomachalek** [comment]
To install a corpus with support for playable audio chunks, the most important thing is to have a mapping between some structure and audio files. Let's say you have a spoken corpus where each transcribed speech/utterance is wrapped in a structure `<sp>` and also let's assume (for the sake of simplicity) you have a single big audio file covering the whole corpus. Then:
- you must be able to cut the individual audio chunks in such a way they match the transcription's `<sp>` tags. 
- each chunk should have a unique name (e.g. based on start time or some auto-generated ID)
- the name of the file must be put into the `<sp>` structure as a new attribute (e.g. `soundfile`) 
- a respective corpus must be configured (I assume `default_corparch` plugin which relies on an XML configuration) as follows:

```xml
<kontext>
  <corplist>
    ...
    <corpus ident="my_spoken_corpus" speech_segment="sp.soundfile" />
    ...
  </corplist>
</kontext>
```

A respective vertical source then may look like this 

```
<sp soundfile="sp1_time000000.mp3">
Hi
John
</sp>
<sp soundfile="sp1_time000931.mp3">
Hi
Jane
</sp>
....
```

The files should be put into a special directory configured in `config.xml` in `corpora/speech_files_path`. Here an additional subdirectory named after a respective corpus must be created for each spoken corpus. E.g. `/var/opt/sound-files/my_spoken_corpus`. Each individual audio file for the corpus goes there. So the final path of a file is actually something like `/var/opt/sound-files/my_spoken_corpus/sp1_time000000.mp3`.

In case there is too much sound (~ tens of thousands an more) files per corpus you can consider putting files into further subdirectories for better filesystem performance (this depends on used filesystem).  To do this automatically you can e.g. create an md5 hash of the file name (in Python: `hashlib.md5('sp1_time000000.mp3'.encode()).hexdigest()`) and use first two letters as additional subdirectories: `/var/opt/sound-files/my_spoken_corpus/4/e/sp1_time000000.mp3`. In such case, the `sp.soundfile` attribute value must include the additional subdirectory: 

```
...
<sp soundfile="4/e/sp1_time000000.mp3">
...
```

**Comment by fishfree** [comment]
@tomachalek Many thanks. Still wait for your whole documentation, please.
