### ISSUE TITLE
Freq charts l10n: English labels of controls

### ISSUE THREAD

**Issue by dlukes** [czcorpus/kontext#4728]
Czech:

![image](https://user-images.githubusercontent.com/2734517/152382913-50b54762-60ea-48e8-a47c-a7c40ef3ba92.png)

English:

![image](https://user-images.githubusercontent.com/2734517/152383016-007f28b8-ff53-4458-93ea-f15ab98f099a.png)

I would suggest to pull the "by" out of "by relative / absolute frequency" in the English version, and change "Sort" to "Sort by" -- like in the Czech version. It makes more sense, also when using these strings as x-axis labels in the charts.

**Comment by tomachalek** [comment]
There were good intentions in the beginning of this but the result is a mess 😇 
I wanted to solve the "Sort [alphabetically]" vs. "Sort by [an attribute]" problem by moving the "by" to respective options. But the translation key is also used elsewhere which made things even worse. So I'm going to reverse the change. Do you think it's acceptable to have the label "Sort by" along with the value "alphabetically"?

**Comment by dlukes** [comment]
Ah right, I understand :) "Sort by: alphabetically" isn't optimal, obviously, but I think going down this road has more advantages than what we currently have, especially if "alphabetically" isn't the default option.

One alternative that comes to mind: "Sort by: A-z", which is sometimes used as a shorthand for "alphabetically" in UIs, and since it's not an adverb, it sounds less jarring in the context of "Sort by". On the other hand, if KonText typically uses the word "alphabetically" to express this meaning in the English localization, sticking with it would have the advantage of being consistent, which is always a nice thing.
