### ISSUE TITLE
Flexible or 2-line query input element for CQL mode

### ISSUE THREAD

**Issue by tomachalek** [czcorpus/kontext#476]
It would be desirable if the query input element (especially the CQL one) was either flexible or solved as a 2-line textarea (just like e.g. GoogleTalk's input box).

**Comment by stranak** [comment]
A flexible one sounds good. One like this very commenting box in Github that is flexible with additional footer line for a quick help/hint would be really great.

**Comment by michkren** [comment]
I agree, the input line is often too short, especially when entering a CQL query. As a solution, I would prefer a flexible one with one-line default that would resemble the current input line in its basic state.

**Comment by tomachalek** [comment]
A test version can be seen here: http://kontext-test.korpus.cz/first_form

**Comment by tomachalek** [comment]
I consider this fixed. Let's wait for some end-user responses and create more specific ticket(s) if needed.
