### ISSUE TITLE
Wrong order of selected positional attributes to display

### ISSUE THREAD

**Issue by dlukes** [czcorpus/kontext#5081]
The selection interface shows positional attributes in the order they're listed in the registry file, i.e. in the order of the columns in the vertical source. However, in the concordance, the attribute values are sorted alphabetically by attribute name, except for the primary attribute which is always listed first.

E.g. in the `dialekt_v2_ort` corpus, check `word [dial]`, `tag` and `dial` as the attributes to display. They will be listed in the order `word [dial]`, `dial` and `tag`, whichever display option (in the concordance, mouseover, separate line etc.) is chosen.

IIRC, historically, the behavior was to show the attribute values in the same order they occur in the selection interface / registry file / vertical source. This seems like the correct behavior IMO.

**Comment by michkren** [comment]
I would like to support the David's opinion, alphabetical sorting is not what a user would expect here.

**Comment by tomachalek** [comment]
Already fixed.
