### ISSUE TITLE
Permalink vs. query editing

### ISSUE THREAD

**Issue by dlukes** [czcorpus/kontext#5115]
1. Run a query.
2. Create a permanent link via the *Concordance* menu.
3. Edit the query via the breadcrumb navigation.
4. Try to create a permanent link for the new concordance. The previous permalink will be displayed instead, falsely claiming that the current (modified) query is already archived.

Workaround: Do a hard refresh of the page.

**Comment by tomachalek** [comment]
This should be already resolved.
