### ISSUE TITLE
Feature suggestion: Allow empty queries with Restrict search

### ISSUE THREAD

**Issue by dlukes** [czcorpus/kontext#5118]
Users sometimes want to search for *any* content matching the criteria they define via *Restrict search*. This is currently only (?) achievable if you know CQL and enter e.g. `[]` into the query box.

Maybe it would be worth it to allow the query box to be empty when *Restrict search* contains any selected criteria, and default to `[]` as the query in that case?

**Comment by michkren** [comment]
I am not sure whether this would actually be beneficial. I think that in vast majority of such cases (when the query box is empty and, at the same time, any _Restrict search_ criteria entered), the user most probably simply forgot to enter the query. It is also hard for me to think of a use case when it makes sense to examine every token from a given selection of documents, so this feature could be misleading.

**Comment by dlukes** [comment]
> I think that in vast majority of such cases (when the query box is empty and, at the same time, any Restrict search criteria entered), the user most probably simply forgot to enter the query.

If so, what are you worried about that would happen if the feature got implemented? That users won't notice? That they'll have to wait for the query to complete before being able to notice, wasting their time and our computational resources?

> It is also hard for me to think of a use case when it makes sense to examine every token from a given selection of documents, so this feature could be misleading.

The point is to get a sample of a particular subdomain of language. I think it's more intuitive with spoken corpora -- e.g. I'm interested in how people in Moravia speak, but I don't have a particular linguistic feature in mind, I just want to "browse" at first. And then maybe I'll come across a linguistic feature I wasn't aware of or that hadn't occurred to me, and do a more refined search focusing on it.

But I think the same approach can be applied to written corpora too -- start by getting a qualitative feel for the domain you're exploring, see if it can guide you towards interesting research questions.

**Comment by michkren** [comment]
> > I think that in vast majority of such cases (when the query box is empty and, at the same time, any Restrict search criteria entered), the user most probably simply forgot to enter the query.
> 
> If so, what are you worried about that would happen if the feature got implemented? That users won't notice? That they'll have to wait for the query to complete before being able to notice, wasting their time and our computational resources?

No. I just think that when the query box is empty, KonText should notify the user about it. If it silently runs the "[]" query instead, it may first take some time before the users notice that the query result is not what they had in their mind (but are not sure whether they actually typed it in or not). NB: the "[]" query results look like a random concordance, so they may feel like "what the hell is this?". Then, they will have to go back and re-enter the query. In case their favourite way of doing this is simply re-typing it again from the very beginning, they may even lose the on-the-fly subcorpus they have already defined. So this kind of user experience is what I am worried about.

> 
> > It is also hard for me to think of a use case when it makes sense to examine every token from a given selection of documents, so this feature could be misleading.
> 
> The point is to get a sample of a particular subdomain of language. I think it's more intuitive with spoken corpora -- e.g. I'm interested in how people in Moravia speak, but I don't have a particular linguistic feature in mind, I just want to "browse" at first. And then maybe I'll come across a linguistic feature I wasn't aware of or that hadn't occurred to me, and do a more refined search focusing on it.
> 
> But I think the same approach can be applied to written corpora too -- start by getting a qualitative feel for the domain you're exploring, see if it can guide you towards interesting research questions.

Well, I think a new KonText feature should be implemented then.

What I especially don't like about the implicit "[]" query is that we impose (likely) users' intention on them.

**Comment by dlukes** [comment]
> I just think that when the query box is empty, KonText should notify the user about it.

In that case, maybe the notification (which is currently just an error message) could instead be a dialog which asks the user if they want to proceed without constraining the search in the query box, possibly warning them that it might take a while to complete, or that they might want to restrict the search at least via the metadata, if none of that is selected either?

This might be a relatively simple and discoverable way of implementing the feature, without blindly assuming that an empty query box means the user intended to search for `[]`, which I understand is not necessarily the case.

**Comment by tomachalek** [comment]
This feature is already implemented and can be reviewed on our "preview" KonText installation.
