### ISSUE TITLE
FCS v1 module is broken

### ISSUE THREAD

**Issue by tomachalek** [czcorpus/kontext#5128]
Basically, any operation produces some exception.  The fix should be applied to the following versions:

* `0.15.2`
* `0.16`
* `master` (devel)

**Comment by TomazErjavec** [comment]
@tomachalek, pls. mention me when the issue is resolved, so I get notified.

**Comment by tomachalek** [comment]
We have a backport of the most recent KonText FCS module. We're going to test it a bit yet and it should be production ready in a few days.

It will require a slight config.xml upgrade. Here is an example of an CNC configuration:

```xml
<kontext>
...
    <fcs>
        <database_title>Czech National Corpus Endpoint</database_title>
        <database_description>A selection of Czech flagship CNC corpora</database_description>
        <search_attributes>
            <item>lemma</item>
            <item>lc</item>
            <item>word</item>
        </search_attributes>
        <corpora>
            <item>syn2020</item>
            <item>oral_v1</item>
        </corpora>
    </fcs>
    ...
</kontext>
```

As you can see, it implies that the `search_attributes` and concrete corpora must be selected in a way that all the attributes can be found in all the corpora. And all the listed corpora must be already configured for KonText (e.g. via a dedicated xml file).

**Comment by tomachalek** [comment]
Everything seems ok. The endpoint now validates without errors:
![image](https://github.com/czcorpus/kontext/assets/439098/ba88dfbf-04d1-45e5-809c-4dc23b87d267)

**Comment by tomachalek** [comment]
A new version 0.15.3 has been published to include this fix (https://github.com/czcorpus/kontext/releases/tag/v0.15.3)
