### ISSUE TITLE
Dockerized app running error.

### ISSUE THREAD

**Issue by Fireblossom** [czcorpus/kontext#5655]
Hi,
I would like to run Kontext in my container but I can't manage to run it, neither the basic configuration instance nor the production grade instance works.

This is the error log for basic configuration instance:
```
rq-worker_1     | AttributeError: module 'rqworker' has no attribute ''
...
kontext_1       | RuntimeError: FileAccessError (/var/lib/manatee/data/susanne/doc.file.rev.idx) in MapBinFile:stat [No such file or directory]
```
The frontend returns `Failed to process your request. please try again later or contact system support.`
Also, I can't register users, the backend will prompt SMTP error:
```
smtplib.SMTPServerDisconnected: please run connect() first
```

This is the error log for production grade instance:
```
mariadb_1       | 2023-03-02  8:30:40 5 [Warning] Access denied for user 'kontext'@'172.18.0.6' (using password: YES)
rq-worker_1     | Integration environment still not available. Reason: 1045 (28000): Access denied for user 'kontext'@'172.18.0.6' (using password: YES)
...
mariadb_1       | 2023-03-02  8:30:40 6 [Warning] Access denied for user 'kontext'@'172.18.0.5' (using password: YES)
kontext_1       | 2023-03-02 08:30:40,203 [plugins.mysql_integration_db] WARNING: Integration environment still not available. Reason: 1045 (28000): Access denied for user 'kontext'@'172.18.0.5' (using password: YES)
```

These occur in 1.16.2 release.

I need your help, Thanks!

**Comment by tomachalek** [comment]
Dear @Fireblossom, I apologize for the delay in responding to your issue, which I am about to close as it is likely no longer relevant. In the meantime, we've fixed several issues related to the Docker installation, so there's a good chance that the problem won't reappear.
