### ISSUE TITLE
AttrNotFound when trying to display own subcorpus info

### ISSUE THREAD

**Issue by dlukes** [czcorpus/kontext#5682]
When I use another user's subcorpus in a query, I can click on its name (in the breadcrumb navigation below the KonText logo) to display information about it:

![other_users_subcorpus](https://user-images.githubusercontent.com/2734517/224725607-98234a91-af68-42d0-a7c0-947382eebd06.png)

However, when I use my own subcorpus, I get `AttrNotFound`:

![my_subcorpus](https://user-images.githubusercontent.com/2734517/224725667-59281247-adad-494f-a3f3-9957e80bac2f.png)

**Comment by tomachalek** [comment]
The problem was actually in `syn2015` itself. Our corpus configuration for dynamic attributes `ep_pos` and `ep_case` was missing the `FROMATTR` entry. I've fixed both, registry files and respective configuration entries in our corp. administration so it should be OK by now.

**Comment by dlukes** [comment]
Great, thanks!
