### ISSUE TITLE
KonText cannot start after installing - no module named 'Manatee'

### ISSUE THREAD

**Issue by zralok123** [czcorpus/kontext#6095]
I install KonText according to the instructions in install.md. When I try to start it (step 5 in install.md), it throws a ModuleNotFoundError: No module named 'manatee'.

**Comment by tomachalek** [comment]
Thank you  for reporting the issue. It looks like Manatee-open  installs by default into `/usr/local/local/...` which is an unintentional thing, I guess. Such a path is not implicitly searched by any Linux distribution for any libraries. We've added a hotfix to our installation script and it should work by now.

If you can, please confirm whether this works for you.

**Comment by zralok123** [comment]
Now it seems to throw an error at the end of the installation process:

cp: cannot stat '/usr/local/local/lib/*': No such file or directory
Traceback (most recent call last):
  File "/opt/kontext/scripts/install/install.py", line 101, in <module>
    steps.SetupManatee(KONTEXT_PATH, stdout, stderr, args.no_cert_check).run(
  File "/opt/kontext/scripts/install/steps.py", line 223, in run
    subprocess.check_call(['cp', '/usr/local/local/lib/*',
  File "/usr/lib/python3.10/subprocess.py", line 369, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['cp', '/usr/local/local/lib/*', '/usr/local/lib']' returned non-zero exit status 1.

**Comment by tomachalek** [comment]
We've just published another fix... Can you please test it again? Thank you.

**Comment by zralok123** [comment]
This seems to work perfectly. KonText is now able to start. Thank you for solving the issue.
