### ISSUE TITLE
Add support for n-grams in the word-list section

### ISSUE THREAD

**Issue by tomachalek** [czcorpus/kontext#795]
... just like in (No)SkE. 

The problem is that (at least in case of our installation) they don't work. The issue must be investigated further.

**Comment by michkren** [comment]
I confirm that n-grams don't work in our installation (tested on word form 2-grams in oral2008, a 1-million-tokens corpus, with default settings), but they do work on the official SkE site at http://the.sketchengine.co.uk

**Comment by michkren** [comment]
Maybe a related issue: Anna has just found out that KonText does not display regular word lists from _subcorpora_, although word lists from the whole corpora do get displayed without any problems.

**Comment by tomachalek** [comment]
Unfortunately, N-grams support is apparently a SkE feature.
