### ISSUE TITLE
can't save collocation list

### ISSUE THREAD

**Issue by dlukes** [czcorpus/kontext#804]
Steps to reproduce:

1. run Query
2. generate Collocations
3. try to Save the result (whichever format)

This results in the following error:

```
unsupported operand type(s) for +: 'int' and 'unicode'
```

Sounds like an explicit `unicode()` conversion is missing somewhere in the code that generates the export...

Affects both the 0.7.x and 0.8.x series. Since this should be a core feature, I think we need a bugfix in the release.

**Comment by tomachalek** [comment]
(Our production version is planned to be updated today between 21 and 22 hours.)

**Comment by dlukes** [comment]
Awesome, thanks a lot! :)
