### ISSUE TITLE
Add support for corpora groups

### ISSUE THREAD

**Issue by tomachalek** [czcorpus/kontext#842]
1. user record should contain user's group entry
2. each corpus should have a list of groups it belongs to

This will be uses to optimize loading of corpora lists.

**Comment by stranak** [comment]
Whan there are groups, would that be possible to do a group search? I like how sets work in the interface of Korp: [Stringberg selected – 2 corpora](http://spraakbanken.gu.se/korp/#?lang=en&stats_reduce=word&cqp=%5B%5D&corpus=strindbergromaner,strindbergbrev)

**Comment by tomachalek** [comment]
unrecoverable issue / unfinished concept with no actual demand
